### ISSUE TITLE
Initialize-ACMEVault : Vault root path is not empty

### ISSUE THREAD

**Issue by KurtHofman** [ebekker/letsencrypt-win#3]
I'm getting the error Vault root path is not empty while is newly created.

PS C:\Vault> attrib
File not found - C:\Vault\*.*
PS C:\Vault> Import-Module C:\letsencrypt-win\bin\ACMEPowerShell
PS C:\Vault> Initialize-ACMEVault -BaseURI https://acme-staging.api.letsencrypt.org/
Initialize-ACMEVault : Vault root path is not empty
At line:1 char:1
+ Initialize-ACMEVault -BaseURI https://acme-staging.api.letsencrypt.org/
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Initialize-ACMEVault], Exception
    + FullyQualifiedErrorId : System.Exception,LetsEncrypt.ACME.POSH.InitializeVault

Any idea how I can solve this ?

**Comment by Trapulo** [comment]
same problem every kind of test I try

**Comment by josephcooney** [comment]
Add -Force 1 works around the issue. Looking at the code, I think this is because it is trying to create the vault in a folder different to what the documentation leads you to believe, and the folder is not empty.

**Comment by cbergcreate** [comment]
Looks like it's related to the 32 bit powershell - http://stackoverflow.com/questions/11246068/why-dont-net-objects-in-powershell-use-the-current-directory

**Comment by KurtHofman** [comment]
Thanks, this solved the problem : 
mkdir c:\Vault
 cd c:\Vault
[Environment]::CurrentDirectory = (Get-Location -PSProvider FileSystem).ProviderPath

**Comment by ebekker** [comment]
I've introduced a fix in the PS module to address this discrepancy between the .NET and PS notion of what is the cwd.  So it should no longer be necessary to do the kludge suggested by KurtHofman.

As part of this fix, I've also added a new parameter to all module cmdlets ``-VaultProfile`` which right now is an optional path to the root of a vault directory, so you don't necessarily have to have the root as your cwd if you use this parameter.  If you omit it, it defaults to the current PS notion of the file system's CWD.

This is still somewhat of a kludge internally because it involves manipulating (and restoring) the actual .NET CWD during the invocation of the cmdlet, which is not clean.  I intend to eventually fix this when I clean up the Vault Provider facility which will support non-file based vaults (e.g. DBs, cloud storage).
